---
abstract: 'authentication using WebID (FOAF+SSL)'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Module::Pluggable: 0.66
  Test::More: 0.61
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.02'
keywords:
  - Auth
  - Authentication
  - FOAF
  - FOAF+SSL
  - HTTPS
  - SSL
  - Security
  - TLS
  - 'Web ID'
  - WebID
  - X.509
  - x509
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: CGI::Auth::FOAF_SSL
name: CGI-Auth-FOAF_SSL
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
recommends:
  WWW::Finger: 0.100
requires:
  CGI: 0
  CGI::Auth::FOAF_SSL::Agent: 0
  CGI::Session: 0
  Crypt::X509: 0.50
  DateTime: 0
  File::Spec: 0
  LWP::UserAgent: 0
  MIME::Base64: 0
  Math::BigInt: 0
  Object::ID: 0
  RDF::TrineShortcuts: 0.100
  Scalar::Util: 0
  common::sense: 0
  parent: 0
  perl: 5.10.0
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=CGI-Auth-FOAF_SSL
  homepage: https://metacpan.org/release/CGI-Auth-FOAF_SSL
  license: http://dev.perl.org/licenses/
  repository: http://goddamn.co.uk/svn-web/perlmods/browse/CGI-Auth-FOAF_SSL/
version: 1.002
