---
abstract: 'authentication using WebID (FOAF+SSL)'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Module::Pluggable: 0.66
  Test::More: 0.61
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
keywords:
  - WebID
  - FOAF
  - SSL
  - FOAF+SSL
  - Authentication
  - Security
  - HTTPS
  - 'Web ID'
  - TLS
  - x509
  - X.509
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CGI-Auth-FOAF_SSL
no_index:
  directory:
    - inc
    - t
recommends:
  WWW::Finger: 0.100
requires:
  CGI: 0
  CGI::Session: 0
  Crypt::X509: 0.50
  DateTime: 0
  LWP::UserAgent: 0
  MIME::Base64: 0
  Math::BigInt: 0
  RDF::TrineShortcuts: 0.100
  Scalar::Util: 0
  common::sense: 0
  perl: 5.8.0
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=CGI-Auth-FOAF_SSL
  homepage: http://search.cpan.org/dist/CGI-Auth-FOAF_SSL/
  license: http://dev.perl.org/licenses/
  repository: http://goddamn.co.uk/viewvc/perlmods/CGI-Auth-FOAF_SSL/
version: 1.001
