# This file provides instructions for packaging.

@prefix : <http://purl.org/NET/cpan-uri/terms#> .

<http://purl.org/NET/cpan-uri/dist/CGI-Auth-FOAF_SSL/project>
	:perl_version_from _:main ;
	:version_from _:main ;
	:readme_from _:main ;
	:test_requires 
		"Module::Pluggable 0.66" , # why?? do we need this?? did we ever need this??
		"Test::More 0.61" ;
	:recommends
		"WWW::Finger 0.100" ;
	:requires
		"common::sense" ,
		"parent" ,
		"CGI" ,
		"CGI::Session" ,
		"Crypt::X509 0.50" ,
		"DateTime" ,
		"LWP::UserAgent" ,
		"Math::BigInt" ,
		"MIME::Base64" ,
		"Object::ID" ,
		"RDF::TrineShortcuts 0.100" ,
		"Scalar::Util 0" .

_:main <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#fileName> "lib/CGI/Auth/FOAF_SSL.pm" .

