# This file provides instructions for packaging.

@prefix : <http://purl.org/NET/cpan-uri/terms#> .

<http://purl.org/NET/cpan-uri/dist/CGI-Auth-FOAF_SSL/project>
	:perl_version_from _:main ;
	:version_from _:main ;
	:readme_from _:main ;
	:test_requires 
		"Test::More 0.61" ;
	:requires
		"Any::Moose" ,
		"CGI",
		"CGI::Session",
		"Web::ID 1.921" .

_:main <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#fileName> "lib/CGI/Auth/FOAF_SSL.pm" .

